import type { StyleConfig, StyleId } from "./types";

export const MARTIAL_ARTS: StyleConfig[] = [
  {
    id: "boxing",
    name: "Boxing",
    description: "Heavy hand combos, fast dodges, no kicks",
    color: "#e74c3c",
    unlockCost: 0,
    coachName: "Coach Ray",
    coachTag: "Ex-heavyweight champion",
    dodgeMultiplier: 1.4,
    counterMultiplier: 1.2,
    combos: [
      { inputs: ["P"], name: "Jab", damage: 8 },
      { inputs: ["P", "P"], name: "Double Jab", damage: 18 },
      { inputs: ["P", "P", "P"], name: "Triple Jab", damage: 28 },
      { inputs: ["P", "K"], name: "Cross-Uppercut", damage: 22 },
      { inputs: ["K"], name: "Body Hook", damage: 14 },
      { inputs: ["K", "K"], name: "Double Hook", damage: 24 },
      { inputs: ["P", "P", "K"], name: "Jab-Cross-Hook", damage: 38, isMega: true },
    ],
  },
  {
    id: "kickboxing",
    name: "Kickboxing",
    description: "Balanced roundhouses and fluid combinations",
    color: "#f39c12",
    unlockCost: 20,
    coachName: "Coach Nadia",
    coachTag: "K-1 World Cup finalist",
    dodgeMultiplier: 1.2,
    counterMultiplier: 1.3,
    combos: [
      { inputs: ["P"], name: "Jab", damage: 7 },
      { inputs: ["K"], name: "Roundhouse", damage: 16, isKick: true },
      { inputs: ["P", "K"], name: "Jab-Roundhouse", damage: 22, isKick: true },
      { inputs: ["K", "P"], name: "Kick-Punch", damage: 20 },
      { inputs: ["K", "K"], name: "Double Kick", damage: 30, isKick: true },
      { inputs: ["P", "P", "K"], name: "Triple Combo", damage: 36, isMega: true },
      { inputs: ["K", "K", "P"], name: "Flying Kick Finish", damage: 50, isKick: true, isMega: true, isHighRisk: true },
    ],
  },
  {
    id: "bjj",
    name: "BJJ",
    description: "Brazilian Jiu-Jitsu: massive counter damage",
    color: "#3498db",
    unlockCost: 20,
    coachName: "Coach Gracie",
    coachTag: "Royce lineage black belt",
    dodgeMultiplier: 1.0,
    counterMultiplier: 2.0,
    combos: [
      { inputs: ["P"], name: "Grab", damage: 6 },
      { inputs: ["K"], name: "Leg Trip", damage: 12, isKick: true },
      { inputs: ["P", "P"], name: "Collar Tie", damage: 18 },
      { inputs: ["K", "P"], name: "Sweep", damage: 22 },
      { inputs: ["P", "K"], name: "Takedown", damage: 28, isMega: true },
      { inputs: ["P", "P", "K"], name: "Submission Hold", damage: 42, isMega: true },
    ],
  },
  {
    id: "aikido",
    name: "Aikido",
    description: "Redirection — uses the opponent's own force",
    color: "#9b59b6",
    unlockCost: 25,
    coachName: "Sensei Ueshiba",
    coachTag: "5th dan Aikikai",
    dodgeMultiplier: 1.3,
    counterMultiplier: 2.5,
    combos: [
      { inputs: ["P"], name: "Palm Strike", damage: 7 },
      { inputs: ["K"], name: "Redirect Kick", damage: 10, isKick: true },
      { inputs: ["P", "P"], name: "Double Palm", damage: 16 },
      { inputs: ["P", "K"], name: "Harmony Throw", damage: 28, isMega: true },
      { inputs: ["K", "P"], name: "Energy Redirect", damage: 28, isMega: true },
      { inputs: ["P", "P", "K"], name: "Kote-gaeshi", damage: 44, isMega: true },
    ],
  },
  {
    id: "muaythai",
    name: "Muay Thai",
    description: "8 limbs: elbows, knees, heavy low kicks",
    color: "#e67e22",
    unlockCost: 25,
    coachName: "Kru Saenchai",
    coachTag: "4x Lumpinee champion",
    dodgeMultiplier: 1.1,
    counterMultiplier: 1.6,
    combos: [
      { inputs: ["P"], name: "Teep", damage: 9 },
      { inputs: ["K"], name: "Low Kick", damage: 14, isKick: true },
      { inputs: ["P", "K"], name: "Elbow Strike", damage: 26 },
      { inputs: ["K", "K"], name: "Double Knee", damage: 30, isKick: true },
      { inputs: ["P", "P", "K"], name: "Knee Strike", damage: 40, isMega: true, isKick: true },
      { inputs: ["K", "K", "P"], name: "Spinning Elbow", damage: 48, isMega: true, isHighRisk: true },
    ],
  },
  {
    id: "judo",
    name: "Judo",
    description: "Explosive throws and takedowns from clinch",
    color: "#1abc9c",
    unlockCost: 30,
    coachName: "Sensei Kano",
    coachTag: "Olympic team coach",
    dodgeMultiplier: 1.2,
    counterMultiplier: 1.8,
    combos: [
      { inputs: ["P"], name: "Collar Grip", damage: 6 },
      { inputs: ["K"], name: "Foot Sweep", damage: 13, isKick: true },
      { inputs: ["P", "P"], name: "Double Grip", damage: 18 },
      { inputs: ["K", "P"], name: "Shoulder Throw", damage: 28, isMega: true },
      { inputs: ["P", "K"], name: "Hip Throw", damage: 32, isMega: true },
      { inputs: ["P", "P", "K"], name: "Ippon Seoi-nage", damage: 46, isMega: true },
    ],
  },
  {
    id: "taekwondo",
    name: "Taekwondo",
    description: "Lightning kicks — high risk, enormous reward",
    color: "#2980b9",
    unlockCost: 30,
    coachName: "Master Park",
    coachTag: "Olympic gold medalist",
    dodgeMultiplier: 1.3,
    counterMultiplier: 1.2,
    combos: [
      { inputs: ["P"], name: "Jab", damage: 6 },
      { inputs: ["K"], name: "Front Kick", damage: 14, isKick: true },
      { inputs: ["K", "K"], name: "Double Kick", damage: 26, isKick: true },
      { inputs: ["P", "K"], name: "Jump Kick", damage: 30, isKick: true, isHighRisk: true },
      { inputs: ["K", "K", "K"], name: "Triple Kick", damage: 40, isKick: true, isMega: true },
      { inputs: ["P", "P", "K"], name: "Spinning Heel", damage: 52, isKick: true, isMega: true, isHighRisk: true },
    ],
  },
  {
    id: "kungfu",
    name: "Kung Fu",
    description: "Five-animal forms with deceptive strikes",
    color: "#c0392b",
    unlockCost: 35,
    coachName: "Sifu Wong",
    coachTag: "Wing Chun lineage master",
    dodgeMultiplier: 1.35,
    counterMultiplier: 1.7,
    combos: [
      { inputs: ["P"], name: "Crane Strike", damage: 8 },
      { inputs: ["K"], name: "Dragon Sweep", damage: 13, isKick: true },
      { inputs: ["P", "P"], name: "Praying Mantis", damage: 19 },
      { inputs: ["K", "P"], name: "Tiger Claw", damage: 27, isMega: true },
      { inputs: ["P", "K"], name: "Leopard Rush", damage: 31, isMega: true },
      { inputs: ["P", "P", "K"], name: "Five Animal Form", damage: 48, isMega: true },
    ],
  },
  {
    id: "mma",
    name: "MMA",
    description: "Mixed everything — adaptable and unpredictable",
    color: "#7f8c8d",
    unlockCost: 50,
    coachName: "Coach Trevor",
    coachTag: "UFC corner veteran",
    dodgeMultiplier: 1.25,
    counterMultiplier: 1.5,
    combos: [
      { inputs: ["P"], name: "Jab", damage: 8 },
      { inputs: ["K"], name: "Low Kick", damage: 13, isKick: true },
      { inputs: ["P", "P"], name: "1-2 Combo", damage: 20 },
      { inputs: ["K", "P"], name: "Clinch Knee", damage: 26, isKick: true },
      { inputs: ["P", "K"], name: "Shoot Double-Leg", damage: 34, isMega: true },
      { inputs: ["P", "P", "K"], name: "Ground & Pound", damage: 45, isMega: true },
      { inputs: ["K", "K", "P"], name: "Spinning Back Kick", damage: 54, isKick: true, isMega: true, isHighRisk: true },
    ],
  },
  {
    id: "wrestling",
    name: "Wrestling",
    description: "Dominant clinch control and crushing slams",
    color: "#d35400",
    unlockCost: 30,
    coachName: "Coach Demetrius",
    coachTag: "NCAA Division I champion",
    dodgeMultiplier: 0.9,
    counterMultiplier: 1.9,
    combos: [
      { inputs: ["P"], name: "Collar Tie", damage: 7 },
      { inputs: ["K"], name: "Ankle Pick", damage: 12, isKick: true },
      { inputs: ["P", "P"], name: "Duck Under", damage: 19 },
      { inputs: ["K", "P"], name: "Single Leg", damage: 28, isMega: true },
      { inputs: ["P", "K"], name: "Double Leg", damage: 34, isMega: true },
      { inputs: ["P", "P", "K"], name: "German Suplex", damage: 50, isMega: true },
    ],
  },
];

export function getStyle(id: StyleId): StyleConfig {
  return MARTIAL_ARTS.find((s) => s.id === id) ?? MARTIAL_ARTS[0]!;
}
